.TH "api Directory Reference" 3 "Tue Jan 7 2020" "Version 1.0" "Personal Blog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
api Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBauthenticate\&.php\fP"
.br
.ti -1c
.RI "file \fBchangeTheme\&.php\fP"
.br
.ti -1c
.RI "file \fBgetImages\&.php\fP"
.br
.ti -1c
.RI "file \fBlogout\&.php\fP"
.br
.ti -1c
.RI "file \fBregister_user\&.php\fP"
.br
.ti -1c
.RI "file \fBstoreImg\&.php\fP"
.br
.in -1c
