.TH "views/imageGalleryBody.php" 3 "Tue Jan 7 2020" "Version 1.0" "Personal Blog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
views/imageGalleryBody.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$files\fP = scandir($path)"
.br
.ti -1c
.RI "\fB$values\fP = array_values($files)"
.br
.ti -1c
.RI "\fB$images\fP = '['"
.br
.ti -1c
.RI "\fBforeach\fP ( $values as $file)"
.br
.ti -1c
.RI "\fB$end\fP = 5"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$end = 5"

.SS "$files = scandir($path)"

.SS "$images = '['"

.SS "$values = array_values($files)"

.SS "foreach($values as $file)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Personal Blog from the source code\&.
