.TH "views/imageGenerator.php" 3 "Tue Jan 7 2020" "Version 1.0" "Personal Blog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
views/imageGenerator.php
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBgetImagesFromFolder\fP ($filepath)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "getImagesFromFolder ( $filepath)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Personal Blog from the source code\&.
