.TH "views/imageGalleryScript.php" 3 "Tue Jan 7 2020" "Version 1.0" "Personal Blog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
views/imageGalleryScript.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$files\fP = scandir($path)"
.br
.ti -1c
.RI "\fB$result\fP = json_encode($files)\&.'\\n'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$files = scandir($path)"

.SS "$result = json_encode($files)\&.'\\n'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Personal Blog from the source code\&.
