.TH "views/myArt.php" 3 "Tue Jan 7 2020" "Version 1.0" "Personal Blog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
views/myArt.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$path\fP =__DIR__ \&. '/\&.\&.'\&. '/assets/myArt'"
.br
.ti -1c
.RI "\fB$javascriptPath\fP = ''/~levymaty/assets/myArt/'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$javascriptPath = ''/~levymaty/assets/myArt/'"

.SS "$path =__DIR__ \&. '/\&.\&.'\&. '/assets/myArt'"

.SH "Author"
.PP 
Generated automatically by Doxygen for Personal Blog from the source code\&.
