.TH "views/navbar.php" 3 "Tue Jan 7 2020" "Version 1.0" "Personal Blog" \" -*- nroff -*-
.ad l
.nh
.SH NAME
views/navbar.php
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBif\fP(isSet($_SESSION['theme'])) \fBelse\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBif\fP (isSet( $_SESSION[ 'theme'])) else"
\fBInitial value:\fP
.PP
.nf
{
  echo '
    <link 
    rel = "stylesheet"
    type = "text/css"
    href = "/~levymaty/css/global\&.css"
    />
    '
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Personal Blog from the source code\&.
